AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - script/*
    - node_modules/**/*
    - vendor/**/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - app/controllers/api/base_controller.rb
    - config/**/*
    - db/seeds.rb
    - lib/tasks/*

Security/Open:
  Exclude:
    - db/seeds.rb

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/api/base_controller.rb
    - app/controllers/api/v1/quotes_controller.rb
